hal_behat_wizard_homepage:
    pattern:  /
    defaults: { _controller: HalBehatWizardBundle:Features:list }
hal_behat_wizard_list:
    pattern:  /hal-behat/list
    defaults: { _controller: HalBehatWizardBundle:Features:list }
