fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hal_behat_wizard_homepage:
    pattern:  /
    defaults: { _controller: HalBehatWizardBundle:Features:list }
hal_behat_wizard_list:
    pattern:  /hal-behat/list
    defaults: { _controller: HalBehatWizardBundle:Features:list }
hal_behat_wizard_edit:
    pattern:  /hal-behat/edit/feature/{feature}
    defaults: { _controller: HalBehatWizardBundle:Features:edit }
hal_behat_wizard_add:
    pattern:  /hal-behat/add
    defaults: { _controller: HalBehatWizardBundle:Features:add}
hal_behat_wizard_synchronize:
    pattern:  /hal-behat/synchronize
    defaults: { _controller: HalBehatWizardBundle:Behat:synchronize }
