parameters:
  hal_behat_wizard.feature_manager.class: Hal\BehatWizardBundle\Manager\FeatureManager

services:
  hal_behat_wizard.feature_manager:
        class: %hal_behat_wizard.feature_manager.class%
        arguments: [@doctrine.orm.entity_manager]
