parameters:
  hbw.wizard_feature_manager.class: Hal\BehatWizardBundle\Manager\Wizard\FeatureManager
  hbw.behat_feature_manager.class: Hal\BehatWizardBundle\Manager\Behat\FeatureManager

services:
  hbw.wizard_feature_manager:
        class: %hbw.wizard_feature_manager.class%
        arguments: [@doctrine.orm.entity_manager]
  hbw.behat_feature_manager:
        class: %hbw.behat_feature_manager.class%
        arguments: [@hbw.wizard_feature_manager, %behat_wizard_tests_folder%]
