parameters:
  hbw.wizard_feature_manager.class: Hal\BehatWizardBundle\Manager\Wizard\FeatureManager
  hbw.behat_feature_manager.class: Hal\BehatWizardBundle\Manager\Behat\FeatureManager
  hbw.behat_manager.class: Hal\BehatWizardBundle\Manager\Behat\BehatManager

services:
  hbw.wizard_feature_manager:
        class: %hbw.wizard_feature_manager.class%
        arguments: [@doctrine.orm.entity_manager]
  hbw.behat_manager:
        class: %hbw.behat_manager.class%
        arguments: [%behat_wizard_tests_folder%]
  hbw.behat_feature_manager:
        class: %hbw.behat_feature_manager.class%
        arguments: [@hbw.wizard_feature_manager, @hbw.behat_manager]
