parameters:
#    hal_behat_wizard.example.class: Hal\BehatWizardBundle\Example

services:
#    hal_behat_wizard.example:
#        class: %hal_behat_wizard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
