hbw.home:
     pattern:  /behat/wizard/list
     defaults: { _controller: HalBehatWizardBundle:Feature:list}

hbw.edit:
     pattern:  /behat/wizard/edit/{feature}
     defaults: { _controller: HalBehatWizardBundle:Feature:edit, feature: ""}
