security:
    providers:
        main:

    firewalls:
        main:
            pattern: /.*
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }