Hal\BehatWizardBundle\Entity\Feature:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    path:
      type: string
      length: 255
    title:
      type: string
      length: 255
    description:
      type: text
      nullable: true
    node:
      type: object
      nullable: true
  oneToMany:
      scenario:
          targetEntity: Scenario
          mappedBy: Feature
  lifecycleCallbacks: {  }
