Hal\BehatWizardBundle\Entity\Scenario:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    path:
      type: string
      length: 255
    title:
      type: string
      length: 255
    node:
      type: object
      nullable: true
  manyToOne:
      feature:
          targetEntity: Feature
  oneToMany:
      state:
          targetEntity: State
          mappedBy: Scenario
  lifecycleCallbacks: {  }
